 1.Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?

 Ans: NumPy is a fundamental library in Python for scientific computing. It offers powerful features for working with multidimensional arrays and performing various mathematical operations efficiently.

NumPy (Numerical Python) is an open source Python library that has a wide range of inbuilt functions.

Advantage of Numpy :NumPy is ideal for handling large amounts of homogeneous (same-type) data, offering significant improvements in speed and memory efficiency. It also provides high-level syntax for a wide range of numerical operations, making it a powerful tool for scientific computing and data processing on the CPU.

2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the
other?


Ans: Both np.mean() and np.average() are functions in NumPy used to calculate averages, but they have different features and use cases. Here’s a detailed comparison:

np.mean()
Purpose: Computes the arithmetic mean of the array elements.

Usage:


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
mean_value = np.mean(arr)
print(mean_value)

3.0


np.average()
Purpose: Computes the weighted average of the array elements, or the arithmetic mean if no weights are provided.

Usage:


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
average_value = np.average(arr)
print(average_value)

# With weights
weights = np.array([1, 1, 1, 1, 1])
weighted_average = np.average(arr, weights=weights)
print(weighted_average)

weights = np.array([1, 2, 3, 4, 5])
weighted_average = np.average(arr, weights=weights)
print(weighted_average)

3.0
3.0
3.6666666666666665


3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D rarays.

Ans:Reversing a NumPy array along different axes can be useful for various tasks, such as data manipulation or preparing data for machine learning. Here's how you can reverse NumPy arrays along different axes, with examples for both 1D and 2D arrays.

Reversing a 1D Array
For a 1D array, reversing is straightforward. You can use slicing to reverse the order of elements.

Example:

In [ ]:
import numpy as np

# Create a 1D array
arr_1d = np.array([1, 2, 3, 4, 5])

# Reverse the array
reversed_arr_1d = arr_1d[::-1]

print("Original 1D array:", arr_1d)
print("Reversed 1D array:", reversed_arr_1d)



Original 1D array: [1 2 3 4 5]
Reversed 1D array: [5 4 3 2 1]


Reversing a 2D Array
For a 2D array, you might want to reverse along specific axes:

Reverse along rows (axis=0): Flips the array vertically.
Reverse along columns (axis=1): Flips the array horizontally.
Example:


In [ ]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("Original 2D array:\n", arr_2d)

# Reverse along rows (axis=0)
reversed_rows = arr_2d[::-1, :]
print("Reversed along rows (axis=0):\n", reversed_rows)

# Reverse along columns (axis=1)
reversed_columns = arr_2d[:, ::-1]
print("Reversed along columns (axis=1):\n", reversed_columns)

# Reverse along both axes
reversed_both = arr_2d[::-1, ::-1]
print("Reversed along both axes:\n", reversed_both)


Original 2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Reversed along rows (axis=0):
 [[7 8 9]
 [4 5 6]
 [1 2 3]]
Reversed along columns (axis=1):
 [[3 2 1]
 [6 5 4]
 [9 8 7]]
Reversed along both axes:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]


4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance

Ans:-In NumPy, determining the data type of elements in an array is straightforward and crucial for efficient memory management and performance. Here's how you can determine the data type and why it matters:

Determining the Data Type

You can use the .dtype attribute of a NumPy array to determine its data type.

Example:

In [ ]:
# Create arrays with different data types
arr_int = np.array([1, 2, 3, 4])
arr_float = np.array([1.0, 2.0, 3.0, 4.0])
arr_complex = np.array([1+2j, 3+4j])

# Print the data types
print("Data type of arr_int:", arr_int.dtype)
print("Data type of arr_float:", arr_float.dtype)
print("Data type of arr_complex:", arr_complex.dtype)

Data type of arr_int: int64
Data type of arr_float: float64
Data type of arr_complex: complex128


Importance of Data Types
1.Memory Management:

Efficient Storage: Different data types require different amounts of memory. For instance, np.float64 (64-bit floating point) uses more memory than np.float32 (32-bit floating point). Choosing the appropriate data type can help manage memory usage efficiently, especially when working with large datasets.
Data Type Precision: The choice of data type affects precision. For example, using np.float32 instead of np.float64 reduces precision but also reduces memory consumption. This trade-off needs to be considered based on the requirements of the task.
2.Performance:

Computational Speed: Operations on arrays with smaller data types (like np.float32 or np.int32) can be faster due to less data being processed and transferred. However, this might come at the cost of precision. Operations on np.float64 are generally more accurate but can be slower.
Hardware Compatibility: Certain hardware, like GPUs, might be optimized for specific data types. For example, GPUs often have special support for single-precision floating-point operations (np.float32), which can lead to performance gains.
3.Compatibility and Interoperability:

Consistency: Ensuring that all arrays in computations have compatible data types prevents unexpected results and errors. For example, mixing np.int32 with np.float64 can lead to type promotion and potential loss of precision.
Integration: When working with other libraries or systems (e.g., interfacing with C/C++ code or using machine learning frameworks), data type consistency is crucial for seamless integration and data exchange.

5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?


Ans:- ndarray stands for "n-dimensional array," and it is the core data structure provided by NumPy for handling large and multi-dimensional arrays of data. Here’s a detailed overview of ndarray and how it compares to standard Python lists:

Defining ndarray

An ndarray is a central data structure in NumPy that represents a grid of values, all of the same type, indexed by a tuple of non-negative integers. The ndarray can be one-dimensional (like a list), two-dimensional (like a matrix), or n-dimensional (like a tensor).

Creating an ndarray Example:

In [2]:
import numpy as np
# Create a 1D ndarray
arr_1d = np.array([1, 2, 3, 4, 5])

# Create a 2D ndarray
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Create a 3D ndarray
arr_3d = np.array([[[1, 2], [3, 4]],
                   [[5, 6], [7, 8]]])
print(arr_1d.ndim)
print(arr_2d.ndim)
print(arr_3d.ndim)



1
2
3


Differences Between ndarray and Python Lists

1.Homogeneity vs. Heterogeneity:

Python Lists: Can store elements of different types (e.g., integers, strings, lists).
ndarray: All elements must be of the same type.

2.Performance:

Python Lists: Operations on lists, especially with large data, can be slow because they require explicit loops and are not optimized for numerical operations.
ndarray: Optimized for performance with support for vectorized operations, making numerical computations faster and more efficient.

3Memory Usage:

Python Lists: More memory overhead due to additional information stored with each element.
ndarray: Uses less memory by storing data in contiguous blocks and only requiring a single type.

4.Multi-dimensional Capability:

Python Lists: Can be nested to create multi-dimensional structures, but this is not as efficient or straightforward as using NumPy arrays.
ndarray: Directly supports multi-dimensional arrays with efficient operations.

5.Mathematical Operations:
Python Lists: Do not support element-wise mathematical operations natively. ndarray: Supports element-wise operations, linear algebra operations, and a wide array of mathematical functions.

6.Shape and Size Attributes:

Python Lists: Do not have built-in attributes for shape and size.
ndarray: Has attributes like .shape, .ndim, and .size that provide detailed information about the array's dimensions and size.

6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations


Ans:- NumPy arrays provide substantial performance benefits over Python lists for large-scale numerical operations. These advantages stem from several factors related to memory management, computational efficiency, and optimized implementations. Here’s a detailed analysis of why NumPy arrays are preferred for large-scale numerical operations:

Performance Benefits of NumPy Arrays

1.Efficient Memory Usage:

Contiguous Memory Allocation: NumPy arrays use contiguous blocks of memory, which reduces overhead and fragmentation compared to Python lists, where each element can be a separate object with additional metadata.
Homogeneous Data Types: NumPy arrays store elements of the same data type, allowing for compact, uniform storage. This avoids the overhead associated with storing different types type-checking that Python lists handle.

2.Vectorized Operations:

Element-wise Operations: NumPy supports vectorized operations, where operations are performed element-wise directly on arrays. This eliminates the need for explicit Python loops, which can be slow due to Python's dynamic typing and interpreter overhead.

Optimized Computations: NumPy operations are implemented in compiled C and Fortran code, which can leverage low-level optimizations and hardware acceleration (e.g., SIMD instructions), resulting in significant speedups for mathematical computations.

3.Broadcasting:

Efficient Handling of Different Shapes: NumPy’s broadcasting mechanism allows arrays of different shapes to be used together in operations without explicit looping or reshaping. This avoids unnecessary data duplication and manipulation, improving performance and memory efficiency.

4.Reduced Overhead:

Fixed Data Types: Unlike Python lists, which store objects with overhead, NumPy arrays store data in a single, contiguous block with a fixed data type. This reduces memory overhead and improves access speed.
Optimized Algorithms: Many mathematical functions and operations in NumPy are implemented using highly optimized algorithms tailored for performance, leveraging efficient numerical libraries like BLAS and LAPACK.

5.Parallelization and Hardware Utilization:

Parallel Processing: NumPy operations can be parallelized to take advantage of multi-core processors and vectorized hardware instructions, speeding up computations significantly.
Integration with Libraries: NumPy is designed to work well with other scientific libraries that can further optimize computations, such as those leveraging GPU acceleration (e.g., CuPy).

6.Advanced Indexing and Slicing:

Efficient Data Manipulation: NumPy’s advanced indexing and slicing mechanisms allow for efficient extraction and manipulation of array elements without the need for explicit loops or complex data structures, which can be slow with Python lists.

Comparison with Python Lists

1. Memory and Performance:

Python Lists: Each element in a Python list is a separate object with additional overhead. Lists are dynamically typed, meaning operations on lists involve frequent type-checking and method calls, which add to the performance cost.
NumPy Arrays: Arrays use contiguous memory blocks and fixed data types, allowing for faster access and manipulation. Operations are performed in compiled code, which is much faster than Python's interpreted operations.

2. Computational Efficiency:

Python Lists: Operations such as element-wise additions or multiplications require explicit loops in Python, which are slow compared to NumPy’s optimized, vectorized operations.
NumPy Arrays: Operations are vectorized, reducing the need for explicit looping and enabling faster execution through low-level optimizations.

3. Scaling:

Python Lists: Performance degrades with the size of the list, particularly for numerical computations that require complex operations or large-scale data handling.
NumPy Arrays: NumPy arrays scale efficiently with data size, thanks to their optimized memory usage and computational efficiency. They handle large datasets and complex operations with ease.
Example

Here’s a simple example comparing the performance of NumPy arrays and Python lists for element-wise addition:

Python Lists:

In [3]:
import time

# Create two large lists
list1 = list(range(1000000))
list2 = list(range(1000000))

# Measure time for element-wise addition
start_time = time.time()
result = [x + y for x, y in zip(list1, list2)]
end_time = time.time()

print("Python list addition time:", end_time - start_time)


Python list addition time: 0.5029587745666504


In [4]:
# Create two large numpy arrays
arr1 = np.arange(1000000)
arr2 = np.arange(1000000)

# Measure time for element-wise addition
start_time = time.time()
result = arr1 + arr2
end_time = time.time()

print("NumPy array addition time:", end_time - start_time)


NumPy array addition time: 0.014918327331542969


7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output


Ans:-In NumPy, vstack() and hstack() are functions used to stack arrays along different axes. Here's a detailed comparison of these functions, along with examples demonstrating their usage and output.

np.vstack() Purpose: Stacks arrays vertically (along the rows). It combines arrays along the first axis (axis=0), resulting in an array where the second axis (columns) remains the same, and the arrays are appended row-wise.

Usage:

In [5]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

# Stack arrays vertically
vstack_result = np.vstack((arr1, arr2))

print("Result of np.vstack:")
print(vstack_result)


Result of np.vstack:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


np.hstack()

Purpose: Stacks arrays horizontally (along the columns). It combines arrays along the second axis (axis=1), resulting in an array where the first axis (rows) remains the same, and the arrays are appended column-wise.

Usage:


In [6]:
# Create some sample arrays
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8], [9, 10]])

# Stack arrays horizontally
hstack_result = np.hstack((arr1, arr2))

print("Result of np.hstack:")
print(hstack_result)

Result of np.hstack:
[[ 1  2  3  7  8]
 [ 4  5  6  9 10]]


8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.

Ans:- In NumPy, fliplr() and flipud() are methods used to reverse the order of elements along specific dimensions of arrays. They are particularly useful for flipping arrays horizontally or vertically. Here’s a detailed explanation of each method and their effects on arrays of different dimensions:

np.fliplr()
Purpose: Flips an array left-to-right (i.e., reverses the order of columns).

Usage:

In [7]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Flip array left-to-right
fliplr_result = np.fliplr(arr_2d)

print("Result of np.fliplr:")
print(fliplr_result)

Result of np.fliplr:
[[3 2 1]
 [6 5 4]
 [9 8 7]]


np.flipud()
Purpose: Flips an array up-to-down (i.e., reverses the order of rows).

Usage:

In [8]:
# Create a 2D array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Flip array up-to-down
flipud_result = np.flipud(arr_2d)

print("Result of np.flipud:")
print(flipud_result)

Result of np.flipud:
[[7 8 9]
 [4 5 6]
 [1 2 3]]


Comparison of fliplr() and flipud()

1.Dimensional Effect:

fliplr(): Affects the columns of a 2D array. It reverses the order of elements along the horizontal axis.
flipud(): Affects the rows of a 2D array. It reverses the order of elements along the vertical axis.

Effect on 1D Arrays:

fliplr(): Not defined for 1D arrays. *flipud(): Reverses the 1D array, similar to using arr[::-1].

Effect on 3D Arrays:

fliplr(): Flips each 2D slice along the horizontal axis (last two dimensions).
flipud(): Flips each 2D slice along the vertical axis (first dimension).

9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

The array_split() method in NumPy is a powerful function used to split an array into multiple sub-arrays. It is particularly useful for dividing arrays into chunks when working with large datasets or when you need to partition data for batch processing.

Functionality of array_split()

The array_split() function divides an array into multiple sub-arrays based on specified criteria. Here’s a breakdown of its functionality and how it handles uneven splits:

Syntax: numpy.array_split(ary, indices_or_sections, axis=0)

ary: The input array to be split.

indices_or_sections: Determines how the array is split. It can be:
An integer: The number of equal-sized chunks to return.
A 1-D array of sorted integers: Specifies the indices at which to split the array.

A list of integers: Specifies the indices at which to split the array. axis: The axis along which to split the array. The default is 0 (rows).
Handling Uneven Splits

When the number of elements in the array cannot be evenly divided by the specified number of sections, array_split() handles the uneven splits by distributing the extra elements as evenly as possible among the resulting sub-arrays.

1. Splitting an Array into a Fixed Number of Chunks:

Example:

In [9]:
# Create a 1D array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Split into 3 equal chunks
chunks = np.array_split(arr, 3)

print("Chunks after splitting into 3 parts:")
for chunk in chunks:
    print(chunk)

Chunks after splitting into 3 parts:
[1 2 3]
[4 5 6]
[7 8 9]


2. Splitting an Array into a Fixed Number of Chunks (Uneven Split):

Example:

In [10]:
# Create a 1D array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Split into 4 chunks
chunks = np.array_split(arr, 4)

print("Chunks after splitting into 4 parts:")
for chunk in chunks:
    print(chunk)


Chunks after splitting into 4 parts:
[1 2 3]
[4 5 6]
[7 8]
[ 9 10]


3. Splitting an Array by Specified Indices:

Example:

In [11]:
# Create a 1D array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Split by indices [2, 5]
chunks = np.array_split(arr, [2, 5])

print("Chunks after splitting by indices [2, 5]:")
for chunk in chunks:
    print(chunk)


Chunks after splitting by indices [2, 5]:
[1 2]
[3 4 5]
[6 7 8 9]


10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?

In NumPy, vectorization and broadcasting are key concepts that significantly enhance the efficiency and performance of array operations. They enable NumPy to perform operations on arrays in a highly optimized manner, minimizing the need for explicit loops and leveraging low-level optimizations. Here’s a detailed explanation of each concept and how they contribute to efficient array operations:

Vectorization

Concept: Vectorization refers to the process of converting operations that would traditionally be performed in a loop into a form that can be executed simultaneously over entire arrays or vectors. This is achieved by using NumPy's built-in operations, which are implemented in compiled code (typically C or Fortran), allowing for fast execution.

How It Works:

Element-wise Operations: NumPy allows operations to be applied element-wise to arrays. For example, adding two arrays or multiplying an array by a scalar. Optimized Implementations: These operations are performed using highly optimized routines that take advantage of hardware-level parallelism and efficient memory access patterns. Example:

python

In [13]:
# Create two large arrays
arr1 = np.random.rand(1000000)
arr2 = np.random.rand(1000000)

# Vectorized operation: element-wise addition
result = arr1 + arr2
print(result)


[0.87568166 1.89090994 0.5025839  ... 0.89190052 1.01196168 0.62964294]


Broadcasting
Concept: Broadcasting is a technique used to perform operations on arrays of different shapes in a way that makes them compatible for element-wise operations. It allows NumPy to handle arrays with different dimensions and sizes without explicitly reshaping them.

How It Works:

Rules: Broadcasting works by aligning the shapes of arrays according to certain rules: If the arrays have different numbers of dimensions, the smaller array is padded with ones on the left side until both arrays have the same number of dimensions. The arrays are then compared element-wise from the last dimension to the first. If the dimensions are not the same, the smaller array is broadcasted to match the shape of the larger array.

Broadcasted Dimensions:

If dimensions are different but compatible (i.e., one is 1 or the same), the smaller dimension is stretched to match the larger dimension. Example:

In [14]:
# Create a 2D array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6]])

# Create a 1D array
arr_1d = np.array([10, 20, 30])

# Broadcast arr_1d to the shape of arr_2d
result = arr_2d + arr_1d

print("Result of broadcasting:")
print(result)


Result of broadcasting:
[[11 22 33]
 [14 25 36]]


##Practical QUESTIONS

1.Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [ ]:
import numpy as np

array = np.random.randint(1, 101, size=(3, 3))
print("Original Array:")
print(array)

# Swap the first and second rows
array[[0, 1]] = array[[1, 0]]
print("\nArray after swapping rows:")
print(array)

# Swap the first and second columns
array[:, [0, 1]] = array[:, [1, 0]]
print("\nArray after swapping columns:")
print(array)


Original Array:
[[32 35 85]
 [67 82 18]
 [51 97 90]]

Array after swapping rows:
[[67 82 18]
 [32 35 85]
 [51 97 90]]

Array after swapping columns:
[[82 67 18]
 [35 32 85]
 [97 51 90]]


2.Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [ ]:
# Generate a 1D NumPy array with 10 elements
array_1d = np.arange(10)
print("Original 1D Array:")
print(array_1d)

# Reshape the 1D array into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)
print("\nReshaped into 2x5 Array:")
print(array_2x5)

# Reshape the 1D array into a 5x2 array
array_5x2 = array_1d.reshape(5, 2)
print("\nReshaped into 5x2 Array:")
print(array_5x2)



Original 1D Array:
[0 1 2 3 4 5 6 7 8 9]

Reshaped into 2x5 Array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaped into 5x2 Array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


3.Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [ ]:

# Create a 4x4 array with random float values
array_4x4 = np.random.random((4, 4))
print("Original 4x4 Array:")
print(array_4x4)

# Add a border of zeros around the 4x4 array
array_6x6 = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)
print("\n6x6 Array with Zero Border:")
print(array_6x6)



Original 4x4 Array:
[[0.5657587  0.75852221 0.37098498 0.53045848]
 [0.29539238 0.46601429 0.50819995 0.35368901]
 [0.3412618  0.14633696 0.41871312 0.70937285]
 [0.17669883 0.42253152 0.55192938 0.52727589]]

6x6 Array with Zero Border:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.5657587  0.75852221 0.37098498 0.53045848 0.        ]
 [0.         0.29539238 0.46601429 0.50819995 0.35368901 0.        ]
 [0.         0.3412618  0.14633696 0.41871312 0.70937285 0.        ]
 [0.         0.17669883 0.42253152 0.55192938 0.52727589 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


4.Using NumPy, create an array of integers from 10 to 60 with a step of 5

In [ ]:
array = np.arange(10, 61, 5)
print(array)


[10 15 20 25 30 35 40 45 50 55 60]


5.Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element

In [ ]:
# Create a NumPy array of strings
array = np.array(['pwskills', 'data', 'analaytics'])
print("Original Array:")
print(array)

# Apply uppercase transformation
uppercase_array = np.char.upper(array)
print("\nUppercase Array:")
print(uppercase_array)

# Apply lowercase transformation (although the original array is already in lowercase)
lowercase_array = np.char.lower(array)
print("\nLowercase Array:")
print(lowercase_array)

# Apply title case transformation
title_case_array = np.char.title(array)
print("\nTitle Case Array:")
print(title_case_array)

# Apply capitalize transformation
capitalize_array = np.char.capitalize(array)
print("\nCapitalize Array:")
print(capitalize_array)

Original Array:
['pwskills' 'data' 'analaytics']

Uppercase Array:
['PWSKILLS' 'DATA' 'ANALAYTICS']

Lowercase Array:
['pwskills' 'data' 'analaytics']

Title Case Array:
['Pwskills' 'Data' 'Analaytics']

Capitalize Array:
['Pwskills' 'Data' 'Analaytics']


6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [ ]:
words_array = np.array(['course', 'numpy', 'assignment'])
print("Original Array:")
print(words_array)

# Insert a space between each character of every word
spaced_words_array = np.char.join(' ', words_array)
print("\nArray with Spaces Between Characters:")
print(spaced_words_array)

Original Array:
['course' 'numpy' 'assignment']

Array with Spaces Between Characters:
['c o u r s e' 'n u m p y' 'a s s i g n m e n t']


7.Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.


In [ ]:
array1 = np.array([[3, 2, 7], [4, 8, 9]])
array2 = np.array([[4,5,1], [2,5,6]])

print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)

# Element-wise addition
addition = np.add(array1, array2)
print("\nElement-wise Addition:")
print(addition)

# Element-wise subtraction
subtraction = np.subtract(array1, array2)
print("\nElement-wise Subtraction:")
print(subtraction)

# Element-wise multiplication
multiplication = np.multiply(array1, array2)
print("\nElement-wise Multiplication:")
print(multiplication)

# Element-wise division
division = np.divide(array1, array2)
print("\nElement-wise Division:")
print(division)

Array 1:
[[3 2 7]
 [4 8 9]]

Array 2:
[[4 5 1]
 [2 5 6]]

Element-wise Addition:
[[ 7  7  8]
 [ 6 13 15]]

Element-wise Subtraction:
[[-1 -3  6]
 [ 2  3  3]]

Element-wise Multiplication:
[[12 10  7]
 [ 8 40 54]]

Element-wise Division:
[[0.75 0.4  7.  ]
 [2.   1.6  1.5 ]]


8.Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [ ]:
identity_matrix = np.eye(5)
print("5x5 Identity Matrix:")
print(identity_matrix)

# Extract the diagonal elements
diagonal_elements = np.diag(identity_matrix)
print("\nDiagonal Elements:")
print(diagonal_elements)

5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
[1. 1. 1. 1. 1.]


9.Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array


In [ ]:
# Generate a NumPy array of 100 random integers between 0 and 1000
random_array = np.random.randint(0, 1000, size=100)
print("Random Array:")
print(random_array)

def is_prime(n):
    """Check if a number is a prime number."""
    if n <= 1:
        return False
    if n <= 3:
        return True
    if n % 2 == 0 or n % 3 == 0:
        return False
    i = 5
    while i * i <= n:
        if n % i == 0 or n % (i + 2) == 0:
            return False
        i += 6
    return True

# Find all prime numbers in the array
primes = np.array([x for x in random_array if is_prime(x)])
print("\nPrime Numbers in Array:")
print(primes)

Random Array:
[237 431 488 458 115 386 359 795 934 384 185 712 972 932 284 236  29 948
 415 527 539 839 303 922 976 768 483 752 200 464 425  97 124 356 654 535
 788 407 990 839 490  34  50 743 546 477 106 587 922 314 954 505 577 927
  51 572 594 270 933 323 711 215 153 424 999  37 973 831 181 315 669 853
 227 596 713 902 183 304 176 410 602 102 795  97 636 167 628 299 951 201
 799 269  28 672  27 173 887   2 351  88]

Prime Numbers in Array:
[431 359  29 839  97 839 743 587 577  37 181 853 227  97 167 269 173 887
   2]


10.Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages

In [ ]:
#Generate daily temperatures for a month (30 days)
np.random.seed(0)  # For reproducibility
daily_temperatures = np.random.uniform(low=0, high=35, size=30)  # Temperatures between 0 and 35 degrees
print("Daily Temperatures for the Month:")
print(daily_temperatures)

#Reshape the array to represent weeks (assuming 30 days = 4 weeks + 2 extra days)
#Reshape to 5 weeks of 6 days
reshaped_temperatures = daily_temperatures.reshape(5, 6) #Change the dimensions of the reshaped array to 5x6
print("\nReshaped Temperatures (5 weeks x 6 days):")
print(reshaped_temperatures)

#Calculate weekly averages
weekly_averages = np.mean(reshaped_temperatures, axis=1)
print("\nWeekly Averages:")
print(weekly_averages)


Daily Temperatures for the Month:
[19.20847264 25.03162782 21.09671816 19.0709114  14.82791798 22.60629396
 15.31555239 31.21205503 33.72819662 13.42045316 27.71037633 18.51132219
 19.88155964 32.39588234  2.48626204  3.04952549  0.70764391 29.14169459
 27.23548628 30.45042519 34.25164198 27.97054975 16.15177768 27.31852117
  4.13960491 22.39723575  5.01736506 33.0634121  18.26469126 14.5131679 ]

Reshaped Temperatures (5 weeks x 6 days):
[[19.20847264 25.03162782 21.09671816 19.0709114  14.82791798 22.60629396]
 [15.31555239 31.21205503 33.72819662 13.42045316 27.71037633 18.51132219]
 [19.88155964 32.39588234  2.48626204  3.04952549  0.70764391 29.14169459]
 [27.23548628 30.45042519 34.25164198 27.97054975 16.15177768 27.31852117]
 [ 4.13960491 22.39723575  5.01736506 33.0634121  18.26469126 14.5131679 ]]

Weekly Averages:
[20.30699033 23.31632595 14.610428   27.22973367 16.23257949]
